John conroy/user email header
hubmapconsortium/portal-ui pull request #1188
Opened 2020-09-08 20:53 UTC by john-conroy

Fix #1030.

2020-09-08 21:49 UTC, tsliaw approved these changes

2020-09-09 12:43 UTC, mccalluc requested changes
I think the special value `User` should be moved up from the python to the JS. Does that seem ok?

2020-09-09 12:43 UTC, mccalluc commented on context/app/routes_auth.py
> +    user_email = user_info['email'] if 'email' in user_info else 'User'
A little uncomfortable here, and with main.py: 
- I think showing "User" when we don't have an user is a UI choice and I'd like to keep it out of the python.
- If the design changes, we'd need update both of these.
- Muddled semantics: `User` isn't an email, and we would never construct something like `mailto:User`.

2020-09-09 12:43 UTC, mccalluc commented on context/app/static/js/components/Header/LoginButton/LoginButton.spec.js
> +  expect(screen.getByText('Log Out')).toHaveAttribute('href', '/logout');
```suggestion
  // In drop-down:
  expect(screen.getByText('Log Out')).toHaveAttribute('href', '/logout');
```

2020-09-11 22:33 UTC, mccalluc commented
> Should I check the status code for the get request or is this sufficient?

If it's non 200, in all likelihood it will be an html body and the `.json()` will fail, and we'll get a 500... and that seems fine to me. If we learn the API is really flakey _and_ we need to be more reliable than our APIs, then we can worry about special error handling.

2020-09-11 22:34 UTC, mccalluc approved these changes
See note in comment. Approved!

2020-09-14 15:25 UTC, merged