John conroy/search page tutorial
hubmapconsortium/portal-ui pull request #1411
Opened 2020-12-08 22:30 UTC by john-conroy

2020-12-10 20:53 UTC, tsliaw commented
I don't know if this is an issue for others, but when I go from Step 5 to 6, then go back to Step 5, whenever I try to press the 'tile view' button to go forward to step 6 again, it won't allow me to continue/button is non-clickable. This occurs for me on both Chrome and Safari.

2020-12-10 21:07 UTC, john-conroy commented
Should be fixed now @tsliaw.

2020-12-10 23:26 UTC, tsliaw approved these changes

2020-12-11 17:08 UTC, mccalluc reviewed
Lots of little tweaks: Most I'll leave to your judgement, but the places where the logic depends on particular strings in the UI need to be addressed. It would be too easy for someone down the line to make a wording tweak in one context, and not realize what depended on that string.

Running it locally, some issues:

- Little thing: There's still an animation down from the upper left corner of the window... I think it's distracting, but I could be off-base?

- Bigger thing: I worry that there are steps that read like calls-to-action, but if the user actually does that, the tutorial just exits. Like step 2: "Click the View All button to display the entire list of filters in the selected category." If I actually do that, pouf! -- no more tutorial.

- This is just wrong: `Multiple “search terms” should be separated by OR.` All searches are `OR`s... try "male": 41 results, "male kidney": 157, "male OR kidney": still 157.

- "Selecting a bolded arrow will reverse the sorting order. " -> "Click again to reverse the order"

- "Toggle the results display mode between list view and tile view. Click the tile view button above to continue." -> "List View and Tile View". Is it possible to bold the second sentence?

- If I'm a little bit sloppy in the click, and hit the wrong button, the tutorial exits.
<img width="113" alt="Screen Shot 2020-12-11 at 11 55 30 AM" src="https://user-images.githubusercontent.com/730388/101931817-f1f6e980-3ba7-11eb-8491-79057529f39d.png">

- Does the library support using the forward and back keys to move through slides?

- @tsliaw : Is there an idiom for "The End" slides? I read the last slide as another call to action, and when I clicked, the tutorial going away was a surprise.

2020-12-11 17:12 UTC, john-conroy commented on context/app/static/js/components/tutorials/DatasetSearchPrompt/DatasetSearchPrompt.jsx
> +  return isDisplayed ? (
React needs a null here.

2020-12-11 17:12 UTC, john-conroy commented on context/app/static/js/components/tutorials/DatasetSearchPrompt/DatasetSearchPrompt.jsx
> +          Take The Dataset Search Tutorial
@tsliaw

2020-12-11 17:14 UTC, john-conroy commented on context/app/static/js/pages/search/Search.jsx
> +      <SearchHeader component="h1" variant="h2" id="asd">
Sorry, this was accidentally committed while experimenting.

2020-12-11 17:14 UTC, tsliaw commented on context/app/static/js/components/tutorials/DatasetSearchPrompt/DatasetSearchPrompt.jsx
> +          Take The Dataset Search Tutorial
"Begin" sounds better

2020-12-11 17:15 UTC, john-conroy commented on context/app/static/js/theme.jsx
> +    tutorial: 1101, // one higher than zIndex of app bar
App bar gets its z-index from MUI. We could overwrite that value if we'd prefer it to come from our code.

2020-12-11 17:16 UTC, john-conroy commented on context/app/static/js/components/tutorials/DatasetSearchPrompt/DatasetSearchPrompt.jsx
> +  /* TODO enable button based on whether element targeted in the first step has mounted */
I'll add a comment for the issue.

2020-12-11 17:30 UTC, mccalluc commented
Last thought: Where did the text come from about using "OR" in the search? That's a fundamental misunderstanding, and it needs to be corrected.

2020-12-11 17:35 UTC, john-conroy commented on context/app/static/js/components/tutorials/SearchDatasetTutorial/SearchDatasetTutorial.jsx
> +const viewMoreSelector = '#Data-Type > div.sk-refinement-list__view-more-action';
I can make the selectors more flexible. I will remove the `>` following `#Data-Type` for the selectors in applicable steps.

2020-12-11 17:36 UTC, tsliaw commented
> Last thought: Where did the text come from about using "OR" in the search? That's a fundamental misunderstanding, and it needs to be corrected.

This came from the text that Chris provided me for implementing the tutorial. [Google Doc](https://docs.google.com/document/d/1Udg1Dgl4y8iFmlyqyxjAvSegAwVR_OG_Py4T4V99CfM/edit)

2020-12-11 17:39 UTC, john-conroy commented on context/app/static/js/components/tutorials/SearchDatasetTutorial/SearchDatasetTutorial.jsx
> +    // handles when user clicks the overlay
I think the new comments meet your criteria. Could you confirm?

2020-12-11 17:47 UTC, john-conroy commented
> Does the library support using the forward and back keys to move through slides?

It doesn't, but since we're using a custom tooltip we could easily add this. Is it the correct decision for accessibility?

2020-12-11 17:49 UTC, john-conroy commented
> Little thing: There's still an animation down from the upper left corner of the window... I think it's distracting, but I could be off-base?

I disabled the transition animation before requesting review and I can't reproduce this.

2020-12-11 18:00 UTC, tsliaw commented
> * Little thing: There's still an animation down from the upper left corner of the window... I think it's distracting, but I could be off-base?
I'm not able to reproduce this either.

> * "Selecting a bolded arrow will reverse the sorting order. " -> "Click again to reverse the order"
I agree that "Click again to reverse the order." is a lot more clearer. 

> * @tsliaw : Is there an idiom for "The End" slides? I read the last slide as another call to action, and when I clicked, the tutorial going away was a surprise.
Given that the "Next" button becomes "Last" and (6/6) is displayed, I think what is currently displayed should be good enough for now. We can revisit this later if this becomes an issue.

2020-12-11 18:22 UTC, john-conroy commented on context/app/static/js/components/tutorials/TutorialTooltip/TutorialTooltip.jsx
> +        {!isLastStep && title !== 'Toggle Display Mode' && (
This will be removed since we're making it a standard step with a next button.

2020-12-11 18:29 UTC, cebriggs7135 requested changes

2020-12-11 18:29 UTC, cebriggs7135 commented on context/app/static/js/components/tutorials/SearchDatasetTutorial/SearchDatasetTutorial.jsx
> +    disableBeacon: true,
```suggestion
    content: 'To further narrow the relevant datasets, type search terms or phrases in “quotes" into the Search bar. Datasets containing any of the search terms will be returned',
    disableBeacon: true,
```

2020-12-11 19:34 UTC, merged