show rui
hubmapconsortium/portal-ui pull request #1457
Opened 2021-01-13 13:24 UTC by mccalluc

Might move us towards #1439... but I think the goal / design needs to be thought out more clearly. The `rui_location` is accessible... but is showing it (either as a blob of JSON, or as a set of numbers) useful to anyone? Should the real goal be to have the transparent human here?

(Whatever direction this takes, do we want analogous designs for Samples and Datasets? Only on Sample right now.)

(Branched from PR #1450.)

2021-01-13 13:33 UTC, ngehlenborg approved these changes
Based on my interpretation of the code this is looking good as a first step.

2021-01-13 13:38 UTC, mccalluc commented
@ngehlenborg : Sorry -- Should have included a screenshot: Hope you can understand why I'm hesitant.

<img width="599" alt="Screen Shot 2021-01-13 at 8 35 27 AM" src="https://user-images.githubusercontent.com/730388/104459220-73acaf00-557a-11eb-9b7d-23085f60e4bb.png">

2021-01-13 14:18 UTC, ngehlenborg requested changes
Ok, upon review of the screenshot I do not approve. I assumed that was somehow integrated into the dev-search. 

Could we expose the RUI JSON one a separate page, e.g., how we are providing the JSON for the entity pages? 

Or we could try to design a foldable view that maps the data to simple UI?

In the medium term we should aim to show the sample location in the body view (from the CCF EUI), assuming we can put together a component that would allow us to do that. CC @ilan-gold @john-conroy

2021-01-13 14:36 UTC, mccalluc commented
Sorry: I should have made sure there was a design first. Just filed #1462.

2021-01-21 20:12 UTC, mccalluc commented
Pivot: This is what we decided in the meeting:
- At a minimum, just show that it is registered, like the samples
- Nils would like to be able show body view on any sample/dataset page.
- Also show neighboring samples.
- Want to make an integrated search in year 4.
- Blocking on IU may slow us down unacceptably.

2021-01-21 22:53 UTC, mccalluc commented
@Nils:
- We're still ahead of Tiffany's design, but I think this is a stop-gap, and giving us a view on the JSON will make it easier to get to the next phase.
- This PR only covers sample details. I've filed #1478 for dataset details, and dev-search already has filters to find examples.
- I've put the JSON in a summary fold-down, which I think looks good enough, and is the right level of effort for something which should be temporary.
- With line-wrapping and a smaller font, it looks ok.
- I've also made the display of the section contingent on there actually being rui_location: Many samples do not have it.
<img width="557" alt="Screen Shot 2021-01-21 at 5 46 41 PM" src="https://user-images.githubusercontent.com/730388/105422287-790c9800-5c11-11eb-8d53-eb028858b878.png">

2021-01-22 15:01 UTC, ngehlenborg commented
@mccalluc I would prefer if we could come up with a solution that opens the JSON in a separate view. I can't tell from your screenshot how long the expanded text is, but if our intention for now is to make this available to developers, I would prefer to not include it directly on the dataset/sample page. Could we use the approach that we implemented for entity-level view (open separate page via click on icon at top of page)?

2021-01-22 16:09 UTC, mccalluc commented
@ngehlenborg : I'd like to avoid adding new code on the python side, which is where it needs ... but that can be done. Should the link be in the section here, or should it be another little icon button?

2021-01-25 00:03 UTC, ngehlenborg commented
I would add the link in the tissue section.

2021-01-25 16:20 UTC, mccalluc commented
Ok, the front-end work here isn't the right direction. Closing, and starting a new branch.

2021-01-25 16:20 UTC, closed without merging