Mccalluc/ilan gold/nonetype assays
hubmapconsortium/portal-ui pull request #1616
Opened 2021-03-10 15:16 UTC by mccalluc

Replace #1615. Fixes #1614.

- Consistent return types are good: whatever is returned, you can call the method.
- Give a default value for is_mock.

Are there public datasets that would have triggered this, or is there something special about the private datasets that the bug was reported for? Is the plan to keep in communication with IEC so as new types come along, we'll get new visualizations up?

2021-03-10 16:59 UTC, ilan-gold requested changes
Can you add the default `is_mock=False` argument to `ImagePyramidViewConf` and `SPRMViewConf`?  For example, http://localhost:5001/browse/dataset/8944e654613a8a31bc90d936dd0fade6 doesn't work right now.

2021-03-10 20:33 UTC, mccalluc commented
@ilan-gold - Thanks for catching that, and sorry for introducing it: When I opened it up in the IDE, there was a highlight there, so static analysis could have caught this... I filed an issue to see if we've got pylint configured correctly. #1617

2021-03-11 02:08 UTC, ilan-gold approved these changes

2021-03-11 02:08 UTC, ilan-gold commented
Can you merge this in the morning @mccalluc and I'll make a release after?

2021-03-11 15:07 UTC, merged