John conroy/home revision upper grid
hubmapconsortium/portal-ui pull request #1727
Opened 2021-04-12 02:41 UTC by john-conroy

2021-04-14 21:27 UTC, tsliaw approved these changes
Everything looks good to me for all screen sizes. Once you add animation for a smoother transition, the carousel should look great.

2021-04-15 15:32 UTC, mccalluc requested changes
- Right now, there's a big gap between the carousel and the bar charts when the screen is wide -- something will fill that gap?
- On narrow screens, the barchart doesn't seem to be on the page at all... intentional?
- If the images go to a submodule, could you add a readme giving the steps with imagemagick (or tool of your choice) to generate the resolutions we need?
- How do things work if the image doesn't have the right aspect ratio? Is that handled in the CSS, or does the processing pipeline need to pad things out so the ratio is consistent?
- The PNGs themselves are larger than they need to be. I just used the first result on google, and got 50% lossless compression. For the command line, probably `pngcrush`. (Assuming now is the time to optimize delivery? It feels like you've gotten this far, we should make sure we have a good pipeline before moving on... but if we hadn't even gotten into image sizing in this PR, that wouldn't have bothered me either ... ie, I think it makes sense to sort this out while we're thinking about it, but I don't think it's a super high priority in its own right, if that makes sense.)

2021-04-15 15:44 UTC, john-conroy commented
> Right now, there's a big gap between the carousel and the bar charts when the screen is wide -- something will fill that gap?
> On narrow screens, the barchart doesn't seem to be on the page at all... intentional?

Yes, to both questions. Here's a [link to the design](https://www.figma.com/file/cEZdI2tOMByTBW8RQ2kuAm/Home-Page?node-id=555%3A1).

> How do things work if the image doesn't have the right aspect ratio? Is that handled in the CSS, or does the processing pipeline need to pad things out so the ratio is consistent?

I think for the carousel, we should just only use images with the correct ration (16:9).

> The PNGs themselves are larger than they need to be. I just used the first result on google, and got 50% lossless compression. For the command line, probably pngcrush. (Assuming now is the time to optimize delivery? It feels like you've gotten this far, we should make sure we have a good pipeline before moving on... but if we hadn't even gotten into image sizing in this PR, that wouldn't have bothered me either ... ie, I think it makes sense to sort this out while we're thinking about it, but I don't think it's a super high priority in its own right, if that makes sense.)

I used ImageOptim to minify the images, but I'll try another tool.

2021-04-15 15:46 UTC, john-conroy commented on context/app/static/js/components/home-revision/CarouselImage/Carouselmage.jsx
> +function Carouselmage({ src320w, src640w, src800w, src1024w, src1280w, src1392w, alt }) {
Sure, if you feel like it cuts complexity we can reduce the srcset with probably little noticeable issue.

2021-04-15 15:47 UTC, john-conroy commented on context/app/static/js/components/home-revision/ImageCarousel/ImageCarousel.jsx
> +      />
Yeah, this was messier than I'd prefer. An object with an associated util function could be better. Or we could change how we import images, but that'd require a webpack tweak.

2021-04-15 15:48 UTC, john-conroy commented on context/app/static/js/components/home-revision/ImageCarouselControlButtons/ImageCarouselControlButtons.jsx
> +    setSelectedImageIndex(selectedImageIndex === 0 ? numImages - 1 : selectedImageIndex - 1);
Not sure if a mod is much simpler, but sure.

2021-04-19 16:09 UTC, john-conroy commented
Filed #1740 and #1741.

2021-04-19 17:20 UTC, mccalluc reviewed
Looks good:
- I think the mod is a tad simpler, if that's ok with you.
- Fewer images: 320/640/1280 as a geometric series, and 1392, since we have it.

I made PR in the subrepo, but that doesn't need to block this. Thanks for pulling out the images.

2021-04-19 17:20 UTC, mccalluc commented on context/app/static/js/components/home-revision/ImageCarouselControlButtons/ImageCarouselControlButtons.jsx
> +    setSelectedImageIndex(selectedImageIndex === numImages - 1 ? 0 : selectedImageIndex + 1);
```suggestion
    setSelectedImageIndex((selectedImageIndex + 1) % numImages);
```

2021-04-19 17:20 UTC, mccalluc commented on context/app/static/js/components/home-revision/ImageCarouselControlButtons/ImageCarouselControlButtons.jsx
> +    setSelectedImageIndex(selectedImageIndex === 0 ? numImages - 1 : selectedImageIndex - 1);
```suggestion
    setSelectedImageIndex((selectedImageIndex - 1 + numImages) % numImages); // In JS, "%" is remainder, not modulus.
```

2021-04-19 17:20 UTC, mccalluc commented on context/app/static/js/components/home-revision/ImageCarousel/ImageCarousel.jsx
> +      />
```suggestion
      <CarouselImage
        src320w={CCFSlide320w}
        src640w={CCFSlide640w}
        src1280w={CCFSlide1280w}
        src1392w={CCFSlide1392w}
        alt="CCF Portal"
      />
      <CarouselImage
        src320w={AzimuthSlide320w}
        src640w={AzimuthSlide640w}
        src1280w={AzimuthSlide1280w}
        src1392w={AzimuthSlide1392w}
        alt="Azimuth"
      />
```

2021-04-19 17:20 UTC, mccalluc commented on context/app/static/js/components/home-revision/ImageCarousel/ImageCarousel.jsx
> +      />
```suggestion
      <CarouselImage
        src320w={VitessceSlide320w}
        src640w={VitessceSlide640w}
        src1280w={VitessceSlide1280w}
        src1392w={VitessceSlide1392w}
        alt="Vitessce"
      />
```

2021-04-19 17:20 UTC, mccalluc commented on context/app/static/js/components/home-revision/ImageCarousel/ImageCarousel.jsx
> +import CCFSlide1392w from 'portal-images/ccf-slide-1392w.png';
```suggestion
import VitessceSlide320w from 'portal-images/vitessce-slide-320w.png';
import VitessceSlide640w from 'portal-images/vitessce-slide-640w.png';
import VitessceSlide1280w from 'portal-images/vitessce-slide-1280w.png';
import VitessceSlide1392w from 'portal-images/vitessce-slide-1392w.png';
import AzimuthSlide320w from 'portal-images/azimuth-slide-320w.png';
import AzimuthSlide640w from 'portal-images/azimuth-slide-640w.png';
import AzimuthSlide1280w from 'portal-images/azimuth-slide-1280w.png';
import AzimuthSlide1392w from 'portal-images/azimuth-slide-1392w.png';
import CCFSlide320w from 'portal-images/ccf-slide-320w.png';
import CCFSlide640w from 'portal-images/ccf-slide-640w.png';
import CCFSlide1280w from 'portal-images/ccf-slide-1280w.png';
import CCFSlide1392w from 'portal-images/ccf-slide-1392w.png';
```

2021-04-20 19:00 UTC, merged