Added more graphs and style to the diversity page
hubmapconsortium/portal-ui pull request #2046
Opened 2021-08-03 19:28 UTC by Roselkisma

2021-08-03 20:42 UTC, mccalluc requested changes
@Roselkisma , there are changes in here that I think are already deployed. I'm not sure exactly what's going on, but you might try:
```
git checkout main
git pull
git checkout roselkisma/more-graphs-and-style
git merge main
# There may or may not be conflicts at this point.
# Merge and push when problems are resolved.
```
Then re-request review.

2021-08-03 20:42 UTC, mccalluc commented on .vscode/settings.json
> +    "python.pythonPath": "/usr/bin/python"
```suggestion
    "eslint.workingDirectories": ["./context"]
```

Having IDE settings checked in is a grey-area: Sometimes it makes sense to share settings across a team... other times different people may have different preferences. In this case, different devs will be using python binaries at different locations, so this should be reverted.

2021-08-03 20:42 UTC, mccalluc commented on CHANGELOG-chart.md
> +- Chart and table.
These go into the change log: We want something that explains the new feature without assuming context.

2021-08-05 13:46 UTC, ngehlenborg commented
@Roselkisma @mccalluc Has the route for this page already been changed to `.../diversity`?

2021-08-05 18:05 UTC, merged