Mccalluc/publications
hubmapconsortium/portal-ui pull request #2047
Opened 2021-08-03 19:55 UTC by mccalluc

First draft:
<img width="628" alt="Screen Shot 2021-08-03 at 3 43 33 PM" src="https://user-images.githubusercontent.com/730388/128076673-a07501e9-21ef-4374-979f-c2516c919602.png">
- Is other information required?
- Does article metadata need to be in a more structured form, or can it just be markdown?
  - If it should be more structured, rather than putting the data entry burden on the authors, maybe write a script to parse [bioarxive XML](https://www.biorxiv.org/content/early/2021/07/29/2021.07.28.454201.source.xml) and output our yaml?
- Do we need a section of boilerplate text for publications like we have for previews?

Still todo:
- Landing page which lists all publications. (Maybe not needed until there are a few?)
- Adding a link to a menu. (Unclear where it should go.)

2021-08-03 20:58 UTC, ngehlenborg requested changes
It would be good to move the author list below the abstract in this case and format the preprint info and a link to the contact author (new) a bit more prominently. See mockup below. 

Can we insert the author names section between the "Manuscript" and "Contact" section?

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1216518/128085210-459d04c0-8f37-4646-b1b2-6a61f3c8fa2e.png">


We do not need the notification message at the top for these pages.

2021-08-03 20:58 UTC, ngehlenborg commented on context/app/publication/kidney-cell-states-atlas.md
> +[Preprint on Biorxive](https://www.biorxiv.org/content/10.1101/2021.07.28.454201v1)
```suggestion
[Preprint on BioRxiv](https://www.biorxiv.org/content/10.1101/2021.07.28.454201)
```

Unfortunately, bioRxiv adds the version number of the preprint (e.g. "v1") at the end of the URL once you visit the DOI link but redirects to the latest if it is not part of the URL. I removed it here.

2021-08-03 21:32 UTC, ngehlenborg commented on context/app/publication/kidney-cell-states-atlas.md
> +[Preprint on Biorxive](https://www.biorxiv.org/content/10.1101/2021.07.28.454201v1)
Obviously a moot point if we make the other requested changes ...

2021-08-04 13:08 UTC, mccalluc commented
@ngehlenborg -- I'm understanding the sections in order to be:
- Abstract
- Manuscript
- Authors
- Contact

Also: If you care strongly about the presentation, and we're hoping it will not be our responsibility to populate this in the future, then we probably want this information in structured yaml that'd we'd parse and then fill in a UI template, to ensure that each page is consistent. Is that what you want, or is the markdown fine? Either is ok, I just want to make sure the question is considered.

2021-08-04 13:15 UTC, ngehlenborg commented
The order of sections is correct.

Let's stick to the Markdown approach for the moment given the flexibility and since we don't have time to do a comprehensive  requirements analysis for a more structured approach. I see this current approach as version 0 and once we have seen a few publication examples, we can structure this further. The four sections included here will be available for all publications.

2021-08-04 13:33 UTC, mccalluc commented on context/app/static/js/pages/Publication/Publication.jsx
> +        {/* Add description of Publications in general? */}
```suggestion
```

2021-08-04 13:33 UTC, mccalluc commented on context/app/static/js/pages/Publication/Publication.jsx
> +// import { StyledDescription } from './style';
```suggestion
```

2021-08-04 13:34 UTC, mccalluc commented on context/app/static/js/pages/Publication/Publication.jsx
> +  return (
```suggestion
  const { vitData, title, markdown } = props;

  return (
```

2021-08-04 13:37 UTC, mccalluc commented
Now looks like:
<img width="384" alt="Screen Shot 2021-08-04 at 9 31 00 AM" src="https://user-images.githubusercontent.com/730388/128190509-ae146c89-e4c4-4858-8973-d4d280290797.png">
I'm going to branch from this and start work on the index page, but that doesn't need to block this.

2021-08-04 13:48 UTC, ngehlenborg requested changes
Looking great apart from that `mailto:`

2021-08-09 13:14 UTC, mccalluc commented
With comments from Nils addressed, I'm going to assume it would have his approval. This way we can get it out in this release, and show it to the authors to get their buy-in, and get a start on authoring the vitessce config.

2021-08-09 13:15 UTC, merged