Mccalluc/iframes
hubmapconsortium/portal-ui pull request #2127
Opened 2021-09-03 22:06 UTC by mccalluc

Fix #2125

2021-09-07 13:27 UTC, john-conroy requested changes
Maybe there is a better way to compose this, let's talk after standup?

2021-09-07 13:27 UTC, john-conroy commented on context/app/static/js/index.jsx
> +  window.location.pathname.startsWith('/iframe/') ? <Iframe flaskData={flaskData} /> : <App flaskData={flaskData} />,
Adding the `iframe` like this would add its underlying components back to the main bundle undoing some of the deliberate splitting we do later on.

2021-09-07 20:25 UTC, mccalluc commented
ok, so to compare the builds... (there must be a better tool for this?)
```
# build, then
ls -Slh context/app/static/public/ | grep 'js$' | perl -pne 's/.*staff//; s/Sep\s+7\s+\d+:\d+//; s/\.\w+\./.*./' > /tmp/v0.26.0-chunks.txt
# and the same for this feature branch
paste /tmp/v0.26.0-chunks.txt /tmp/iframes-chunks.txt
   7.4M  32.*.js	   7.4M  32.*.js
   6.7M  8.*.js	   6.7M  8.*.js
   1.3M  acb35f241ba3735673b02d5fd9c725de.js	   1.3M  acb35f241ba3735673b02d5fd9c725de.js
   963K  vendors.*.js	   1.1M  vendors.*.js
   947K  11.*.js	   939K  11.*.js
   639K  12.*.js	   630K  12.*.js
   639K  13.*.js	   629K  13.*.js
   322K  5.*.js	   320K  5.*.js
   191K  35.*.js	   184K  35.*.js
   182K  14.*.js	    97K  14.*.js
    74K  main.*.js	    88K  main.*.js
    70K  7.*.js	    70K  7.*.js
...
```
I think the change in `main.*.js` from 74K to 88K is attributable to this, but at the same time, I think dependencies like visx that are in `14.*.js` on `v0.26.0` are shifted over to `vendors`, which increases from 963K to 1.1M.

So, getting the lazy loading right is a good thing, but relatively inconsequential compared to `32.*.js`, I think. I just tried, and

2021-09-07 21:50 UTC, mccalluc commented
Added `lazy`: Comparing the latest state to the base of the branch:
```
paste /tmp/v0.26.0-chunks.txt /tmp/latest-chunks.txt
   7.4M  32.*.js	   7.4M  30.*.js
   6.7M  8.*.js	   6.7M  9.*.js
   1.3M  acb35f241ba3735673b02d5fd9c725de.js	   1.3M  acb35f241ba3735673b02d5fd9c725de.js
   963K  vendors.*.js	   963K  vendors.*.js
   947K  11.*.js	   953K  12.*.js
   639K  12.*.js	   645K  13.*.js
   639K  13.*.js	   644K  14.*.js
   322K  5.*.js	   320K  6.*.js
   191K  35.*.js	   197K  15.*.js
   182K  14.*.js	   118K  16.*.js
    74K  main.*.js	   118K  17.*.js
    70K  7.*.js	    99K  18.*.js
    49K  16.*.js	    81K  8.*.js
    49K  17.*.js	    75K  main.*.js
```
vendors and main stay almost exactly the same, but I don't understand the other changes.

2021-09-08 17:53 UTC, john-conroy approved these changes
As we discussed, you could possibly just lazy load the `Iframe` component for simplicity, but that might be slightly different than what is here - so this works. Thanks!

2021-09-08 18:20 UTC, mccalluc commented
You're right, lazy could be higher: I guess I like the parallelism between Iframe and Routes this way, so it's obvious that the heavy-weight lower components are lazy. Not a big deal either way.

2021-09-08 18:20 UTC, merged