Mccalluc/link to organ page
hubmapconsortium/portal-ui pull request #2206
Opened 2021-10-13 16:24 UTC by mccalluc

Towards #2170. (To close that issue, I'd want to link to a particular organ page, and not just the list.) The motivation for all of this is `Dataset.jsx`: It makes sense to treat the link to the assay and the link to the organ the same way... that entails pulling out the trailing vertical divider and making it explicit everywhere it is needed.

- Is this a good way of approaching the problem?
- Assuming I should set up a containing directory for `VerticalDivider`... unless it can be grouped with something else?
- Right now, this is introducing a vertical alignment problem on the right side of the summary:
<img width="238" alt="Screen Shot 2021-10-13 at 12 21 14 PM" src="https://user-images.githubusercontent.com/730388/137174175-981bf1cd-4510-4492-a09e-92f8eeeb361d.png">

Filing as draft for now.

---

Updated, moved out of draft. Fixes #2252.

2021-11-30 19:44 UTC, mccalluc commented
@john-conroy -- Replaced the VerticalDivider with Typography around `|`... Treating it the same as the text that it it punctuates seems like the easiest way to sort out the base-line alignment issues.

2021-12-01 20:09 UTC, john-conroy commented on context/app/static/js/shared-styles/VerticalDivider.jsx
> +      &nbsp;|&nbsp;
What prompted the change to a pipe?

2021-12-01 20:36 UTC, john-conroy reviewed
I think this is horizontal progress. The previous situation was flawed, but this has its own drawbacks. Not sure what the best direction is as I tried before and didn't make much progress.

2021-12-01 20:36 UTC, john-conroy commented on context/app/static/js/shared-styles/VerticalDivider.jsx
> +      &nbsp;|&nbsp;
I'd also prefer to rely on css for spacing.

2021-12-01 20:36 UTC, john-conroy commented on context/app/static/js/components/detailPage/SummaryItem.jsx
> -`;
I think with the removal of the `VerticalDivider` this component has lost its use. The flex is only used to move the divider and icon in-line, so this is only really needed in situations where the `statusIcon` is passed.

2021-12-01 20:36 UTC, john-conroy commented on context/app/static/js/pages/Dataset/Dataset.jsx
> +      </SummaryItem>
As mentioned above, as is, `SummaryItem` not needed here.

2021-12-01 20:36 UTC, john-conroy commented on context/app/static/js/pages/Sample/Sample.jsx
> +          <SummaryItem>
`SummaryItem` not needed.

2021-12-01 20:36 UTC, john-conroy commented on context/app/static/js/components/detailPage/SummaryData/SummaryData.jsx
>                  <SummaryItem>{`${mapped_data_access_level} Access`}</SummaryItem>
No longer need `SummaryItem` here.

2021-12-01 20:37 UTC, john-conroy commented on context/app/static/js/components/detailPage/SummaryItem.jsx
> -`;
For most cases you can just use `Typography` now.

2021-12-01 21:34 UTC, mccalluc commented
@john-conroy :
- I'll get rid of the `SummaryItem` component entirely, and just use `Typography`
- Use CSS rather than `&nbsp;`
- Difference of opinion about `Divider` vs `|`... For me, it's actually a good thing that `|` is harder to customize, because the default behavior all I want

2022-01-18 18:28 UTC, mccalluc commented
Screenshots of the current state:

wide:
<img width="987" alt="Screen Shot 2022-01-18 at 1 25 01 PM" src="https://user-images.githubusercontent.com/730388/149996685-e012d560-4c6b-40e0-a085-1d24f603dadd.png">

slightly narrower:
<img width="809" alt="Screen Shot 2022-01-18 at 1 25 24 PM" src="https://user-images.githubusercontent.com/730388/149996656-6c5c2802-2472-4704-b707-79343aaa6c0a.png">

Assuming the tests pass on CI, the one thing that still pops out for me is the vertical alignment of the colored circle.

2022-01-18 18:49 UTC, mccalluc commented
Using CSS margin to nudge the icon around:
<img width="85" alt="Screen Shot 2022-01-18 at 1 49 05 PM" src="https://user-images.githubusercontent.com/730388/150000085-77167627-d93f-49cd-b49c-0d9810acfddb.png">

2022-01-18 22:25 UTC, john-conroy requested changes
Prod

<img width="1792" alt="Screen Shot 2022-01-18 at 5 16 27 PM" src="https://user-images.githubusercontent.com/62477388/150027607-7801da05-154e-4ae6-b53a-ecb1cd8be19f.png">

This branch

<img width="1792" alt="Screen Shot 2022-01-18 at 5 16 12 PM" src="https://user-images.githubusercontent.com/62477388/150027612-d5e65c75-9436-462f-94e2-e3a13421bcbc.png">

Could I improve with better component naming, file organization or maybe adding some stories to make it more clear where a component is used?

2022-01-18 22:25 UTC, john-conroy commented on context/app/static/js/components/detailPage/StatusIcon/style.js
> +  margin-bottom: -2.5px;
Can we create a component for typography with an icon which relies on flex to center the items instead of specific margin values?

2022-01-18 22:25 UTC, john-conroy commented on context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
> +            .join(' | ')}
I understand moving from the divider to the pipe for the detail page `Summary` as it doesn't affect the page's appearance, but `EntityHeader` items are meant to be separated by lines which are the full height of its container. Also something has happened and the font size of the text/icons in the `EntityHeader` is different than before.

2022-01-18 22:25 UTC, john-conroy commented on context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
> +            .join(' | ')}
Also missing a divider/pipe between the hubmap id and organ type.

2022-01-18 22:27 UTC, john-conroy commented
I don't think the 'slightly narrower' layout is great, but since it would require an even larger effort than this PR and we've been given the directive to focus on laptops/desktops it probably shouldn't block.

2022-01-19 14:33 UTC, mccalluc commented
Oh: This hadn't even been on my radar:

<img width="1792" alt="Screen Shot 2022-01-18 at 5 16 12 PM" src="https://user-images.githubusercontent.com/62477388/150027612-d5e65c75-9436-462f-94e2-e3a13421bcbc.png">

That makes me think the premise of simplifying by getting rid of `SummaryItem` sent this in a bad direction. Do you think there's anything worth salvaging here? We can talk at standup.

2022-02-17 18:43 UTC, mccalluc commented
Closing and starting over. Trying to replace dividers with pipe characters doesn't work when it's pinned to the top of the window.

2022-02-17 18:43 UTC, closed without merging