Mccalluc/show doi
hubmapconsortium/portal-ui pull request #2460
Opened 2022-02-24 22:27 UTC by mccalluc

Fix #2454
<img width="481" alt="Screen Shot 2022-02-24 at 5 24 18 PM" src="https://user-images.githubusercontent.com/730388/155617725-2fbb3e6d-207e-4311-9190-5aab5ac206b9.png">

(The icon seems a little low... but it seems a little low on Collections, too, and if it should change, I'd prefer that to be an issue separate from this: I don't feel great about the copy and paste of style.js.)

2022-02-28 16:43 UTC, john-conroy requested changes
Remove the `vertical-align:text-bottom` and apply `display: flex` to the `OutboundLink` and the text/icon should be aligned. The dividers in the screenshot seem to be different sizes.

2022-02-28 17:31 UTC, ngehlenborg commented
@john-conroy and @mccalluc If we can get this out before next Monday it will be greatly appreciated. Thanks!

2022-02-28 21:59 UTC, mccalluc commented
@john-conroy , trying to apply your advice, it looked like this:
<img width="82" alt="Screen Shot 2022-02-28 at 4 49 40 PM" src="https://user-images.githubusercontent.com/730388/156064579-1a25800e-49e1-4030-adab-837d2aef8bea.png">
In the last commit I add `align-items: center;` and now it looks like
<img width="89" alt="Screen Shot 2022-02-28 at 4 49 58 PM" src="https://user-images.githubusercontent.com/730388/156064636-fce2f9d0-70be-4a44-b258-0e05bcca304e.png">

(This is also missing the preceding whitespace from the original screenshot.)

I've seen what look like variations in the weight of the vertical bar, too, but on the right side: I don't this PR has anything to do with that problem.

And, if the strings get long, we don't handle it well... but I don't think this is the place to sort that out.
<img width="737" alt="Screen Shot 2022-02-28 at 4 54 34 PM" src="https://user-images.githubusercontent.com/730388/156065476-4a74dc6d-3b1e-44bf-9c89-d230b0926a3f.png">

2022-03-02 14:17 UTC, mccalluc commented
- Replaced by #2472

2022-03-02 14:17 UTC, closed without merging