HMP-183 Fix `entityType` TypeError blocking donor pages
hubmapconsortium/portal-ui pull request #3133
Opened 2023-06-16 20:48 UTC by NickAkhmetov

This PR fixes a minor error in variable referencing; `entityType` was undefined when referenced from flask data due to flask data variables being formatted in `snake_case` instead of `camelCase` for easy searchability between the front/back end.

# Before fix:
https://portal-prod.stage.hubmapconsortium.org/browse/donor/7adf466f027c44278e19b57fb59bacdc
![image](https://github.com/hubmapconsortium/portal-ui/assets/19957804/b45d0402-3d89-4418-9dac-6d5c6b9cb714)

# After fix:
http://localhost:5001/browse/donor/7adf466f027c44278e19b57fb59bacdc
![image](https://github.com/hubmapconsortium/portal-ui/assets/19957804/0dc0ab8d-f902-4aad-a44f-1d1d2db4f54c)

2023-06-16 22:37 UTC, lchoy approved these changes

2023-06-16 23:40 UTC, lchoy requested changes

2023-06-16 23:40 UTC, lchoy commented on  CHANGELOG-hmp-183-fix-donor-derived-samples.md
There's a leading space in the filename that's causing the CI test to fail.

2023-06-17 02:59 UTC, NickAkhmetov commented on  CHANGELOG-hmp-183-fix-donor-derived-samples.md
It should be fixed now. Thanks for catching it!

2023-06-17 12:33 UTC, lchoy approved these changes

2023-06-19 01:47 UTC, lchoy approved these changes

2023-06-20 12:34 UTC, merged