Tkakar/cat 613 add status icon multiassay
hubmapconsortium/portal-ui pull request #3478
Opened 2024-07-23 15:04 UTC by tkakar

This PR merges the addition of status icons to the details page for multi-assay dataset relationships

2024-07-23 15:16 UTC, NickAkhmetov requested changes
Great work! Just a minor suggestion re: using the `Stack` utility instead of introducing a single-use styled component.

2024-07-23 15:16 UTC, NickAkhmetov commented on context/app/static/js/components/detailPage/multi-assay/RelatedMultiAssayLinks/style.ts
> +import styled from 'styled-components';
```suggestion
import { styled } from '@mui/material/styles';
```

Importing the styled utility from MUI will make it more straightforward for us to eventually upgrade to a more performant styling approach (likely https://github.com/mui/pigment-css once it's mainlined in MUI 6). It also makes it easier to access theme values in the styles via TypeScript hints.

2024-07-23 15:16 UTC, NickAkhmetov commented on context/app/static/js/components/detailPage/multi-assay/RelatedMultiAssayLinks/RelatedMultiAssayLinks.tsx
> +        </FlexContainer>
```suggestion
        <Stack direction="row" useFlexGap gap={0.5} alignItems="center">
          {assay_display_name}:<InternalLink href={`/browse/dataset/${uuid}`}>{hubmap_id}</InternalLink>
          <StatusIcon status={status} />
        </Stack>
```

The [MUI `Stack` component](https://mui.com/material-ui/react-stack/) is very useful in cases that call for a flex container on the go 😄

2024-07-23 15:16 UTC, NickAkhmetov commented on context/app/static/js/components/detailPage/multi-assay/RelatedMultiAssayLinks/style.ts
With the suggested change to `Stack` above, we should be able to remove this file.

2024-07-23 15:34 UTC, john-conroy commented on CHANGELOG-add-status-icon-to-multiassay-listing
> +- Added status icon to the processed datasets to differntiate between different runs
This file is missing the `.md` extension.

2024-07-23 15:34 UTC, john-conroy commented on CHANGELOG-fix-changelog-entry.md
> +- Fix changelog formatting for v0.101.1 entries.
This changelog has already been compiled and needs to be removed - sorry this is a pain.

2024-07-23 18:16 UTC, NickAkhmetov commented on CHANGELOG-add-status-icon-to-multiassay-listing.md
> +- Added status icon to the processed datasets to differntiate between different runs
```suggestion
- Added status icon to the processed datasets to differentiate between different runs.
```

Minor spelling fix/added comma at the end - if you can re-request review after fixing this, I'll sign off on it 😄

2024-07-24 14:53 UTC, NickAkhmetov approved these changes
🚀

2024-07-24 14:56 UTC, merged