Fixed assays and samples sections for organs
hubmapconsortium/portal-ui pull request #3487
Opened 2024-07-30 14:31 UTC by tkakar

## Summary

Fixes the assays and samples sections on the detail page for organs. Some organs (such as brain and uterus) had `search:[]` in the yaml files, so the search query was not executed.

## Design Documentation/Original Tickets
Jira ticket: [CAT-770](https://hms-dbmi.atlassian.net/browse/CAT-770)

## Testing
In the Dev env, for organs with datasets, now the samples and assay sections are visible and vice-versa.

## Screenshots/Video
<img width="1304" alt="Screenshot 2024-07-30 at 10 24 40 AM" src="https://github.com/user-attachments/assets/01fea756-7d35-432a-98ca-39a831a13a78">

## Checklist

- [x] Code follows the project's coding standards
  - [x] Lint checks pass locally
  - [x] New `CHANGELOG-your-feature-name-here.md` is present in the root directory, describing the change(s) in full sentences.
- [ ] Unit tests covering the new feature have been added
- [x] All existing tests pass
- [ ] Any relevant documentation in JIRA/Confluence has been updated to reflect the new feature
- [ ] Any new functionalities have appropriate analytics functionalities added

## Additional Notes
To avoid changes in the samples component that underneaths uses a shared component, I added the re-render logic in the Assays component. The idea is that search will be executed for all organs, and the page will be re-rendered  only for the organs that returns 0 searches. The table-of-content also updates based on the presence of those sections.

A side note: I have noticed the assay table and the barchart look a little off. Maybe the vertical grid lines need to be removed from the barchart, or we need a border at the bottom? 
For the table, the bottom looks off, could be inherent from the underlying react component, but when scrolling is needed, the last row is cut off (attached image below).

<img width="1135" alt="Screenshot 2024-07-30 at 10 28 26 AM" src="https://github.com/user-attachments/assets/d53a61a5-1218-452f-a2cc-a54230bbdbcd">

[CAT-770]: https://hms-dbmi.atlassian.net/browse/CAT-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-30 15:27 UTC, john-conroy requested changes
Thanks! A few comments in hopes of simplifying this a bit. I'll ask @NickAkhmetov to chime in and maybe he has an approach to make this simpler than what I've suggested.

2024-07-30 15:27 UTC, john-conroy commented on context/app/static/js/pages/Organ/Organ.tsx
> +  };
Can we just do `const searchTerm = organ?.search ?? organ.name;`

2024-07-30 15:27 UTC, john-conroy commented on context/app/static/js/components/organ/Assays/Assays.jsx
> +  const [bucketData, setBucketData] = useState([]);
Not sure why we would need to add this to state? We can continue to access the buckets as we have.

2024-07-30 15:27 UTC, john-conroy commented on context/app/static/js/components/organ/Assays/Assays.jsx
> +  }, [searchData, onHandleSearchStatus]);
Objects, like `searchData`, and arrays provided in the dependencies are compared by reference and will continuously trigger if not memoized, handled with a custom compare fn, or handled using a custom hook like `useDeepCompareEffect` which performs a deep comparison. In this case, if we wanted to track whether the `searchData` has buckets in state we could define `const hasBuckets = buckets.length` which could then be used in the `useEffect` without issue.

2024-07-30 15:27 UTC, john-conroy commented on context/app/static/js/pages/Organ/Organ.tsx
> +            <Assays organTerms={searchItems} onHandleSearchStatus={handleDataStatus} />
I think we can guarantee that if there are datasets, there are samples, but possibly not the other way around.

2024-07-30 15:27 UTC, john-conroy commented on context/app/static/js/components/organ/Assays/Assays.jsx
>    const { searchData } = useSearchData(query);
I think the simplest approach would just be to lift this to the parent for both `Assays` and `Samples` and avoid using the `useEffect` altogether?

2024-07-30 15:40 UTC, NickAkhmetov commented on context/app/static/js/pages/Organ/Organ.tsx
> +        {shouldDisplaySection[assaysId] && searchHasData && (
Could `searchHasData` be included as part of the `shouldDisplaySection` logic above?

2024-07-31 13:34 UTC, john-conroy approved these changes
Great, thanks!

2024-07-31 14:35 UTC, merged